### ISSUE TITLE
希望可以加上点击翻页或者触屏翻页

### ISSUE THREAD

**Issue by iswlt** [readdig/readdig#7]
手机屏幕本来就小看长文章 ，手指翻页时间长了很酸希望可以加一个翻页按钮，或者触屏翻页

**Comment by RSSxdev** [comment]
请问的是哪里的翻页，首页的滚动翻页，还是正文阅读的上一篇和下一篇的翻页。

**Comment by iswlt** [comment]
正文阅读长篇文章正文的时候希望可以触屏翻页，首页添加一个点击翻页的悬浮组件选文章标题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RSSxdev/Readdig"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RSSxdev/Readdig] 希望可以加上点击翻页或者触屏翻页 (Issue #7)





 
请问的是哪里的翻页，首页的滚动翻页，还是正文阅读的上一篇和下一篇的翻页。
